CREATE TABLE IF NOT EXISTS categories(
    id integer PRIMARY KEY GENERATED BY DEAFULD AS IDENTITY, -- id serial not null primary key,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS products(
    id integer PRIMARY KEY GENERATED BY DEAFULD AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    price text NOT NULL CHECK (price <> ''),
    available BOOLEAN,
    bestSeller BOOLEAN,
    img text NOT NULL CHECK (img <> ''),
    description text NOT NULL CHECK (description <> ''),
    categories integer REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS purchases(
    id integer PRIMARY KEY GENERATED BY DEAFULD AS IDENTITY,
    dateCreate date,
    customer integer,
    products integer[] REFERENCES products(id)
);